Repository Dev-FE-1/Toy_Project_3_Team1, pull requests merged in 2024-08, with the labels that each got.

#8 Feat/router #3 라우터 초기설정
  .eslintrc.cjs
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/index.css
  src/pages/CreatePlaylist.tsx
  src/pages/EditProfile.tsx
  src/pages/Follow.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Page404.tsx
  src/pages/Playlist.tsx
  src/pages/Profile.tsx
  src/pages/Search.tsx
Labels: enhancement

#16 ✨ #15 firebase 초기설정
  .gitignore
  package-lock.json
  package.json
  src/firebase/firebaseConfig.ts
Labels: ✨ Feature

#20 ✨ #19 자동배포 및 수동배포 추가
  .firebase/hosting.ZGlzdA.cache
  .firebaserc
  .github/workflows/click_cd.yml
  .github/workflows/pr_auto_cd.yml
  .github/workflows/test.yml
  firebase.json
Labels: 🍻 Deploy

#21 ✨ #12 로그인 기능 구현
  src/App.tsx
  src/constants/path.ts
  src/hooks/useAuth.ts
  src/hooks/useLogout.ts
  src/layout/Root.tsx
  src/pages/EditProfilePage.tsx
  src/pages/EditPwPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
Labels: ✨ Feature

#25 ☠️ #24 깃헙액션 환경변수 설정
  .github/workflows/click_cd.yml
  .github/workflows/pr_auto_cd.yml
  database.rules.json
  firebase.json
  src/firebase/firebaseConfig.ts
Labels: 🍻 Deploy

#26 📝 #22 레이아웃 css 적용
  package-lock.json
  package.json
  src/assets/myidoru_logo.svg
  src/components/layout/Header.tsx
  src/components/layout/Navbar.tsx
  src/constants/color.ts
  src/constants/font.ts
  src/layout/Root.tsx
  src/main.tsx
  src/pages/EditPwPage.tsx
  src/pages/LoginPage.tsx
  src/styles/GlobalStyles.tsx
Labels: 📝 Design

#35 ✨ #30 회원가입 페이지 생성
  .github/workflows/click_cd.yml
  .github/workflows/pr_auto_cd.yml
  package-lock.json
  package.json
  src/App.tsx
  src/components/Form.tsx
  src/constants/path.ts
  src/hooks/useAuth.ts
  src/layout/Root.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/types/formType.d.ts
Labels: ✨ Feature

#33 ✨ # 22 플레이리스트 추가 페이지 구현
  src/App.tsx
  src/api/playlist/createPlayList.ts
  src/constants/path.ts
  src/pages/CreatePlaylistPage.tsx
  src/pages/ProfilePage.tsx
Labels: ✨ Feature

#40 ☠️ #39 플레이리스트 영상 url 데이터 추가
  src/api/playlist/createPlayList.ts
  src/pages/CreatePlaylistPage.tsx
Labels: ☠️ Fix

#42 [fix] 헤더 및 메뉴의 반응 속도 개선및 깃이모지 업데이트
  .gitmojirc.json
  src/hooks/useAuth.ts
  src/layout/Root.tsx
Labels: 🐱 Chore, ☠️ Fix

#49 ☠️ #48 기존 +1씩 올라가던 playlistId 삭제
  src/api/playlist/createPlayList.ts
Labels: ☠️ Fix

#45 ✨🔨 #38 input/button 공통컴포넌트 제작 및 로그인/비밀찾기 페이지 적용, 리팩토링
  package-lock.json
  src/assets/myidoru_logo.svg
  src/components/common/Button/Button.tsx
  src/components/common/Button/ButtonImage.tsx
  src/components/common/Button/ButtonLink.tsx
  src/components/common/Input/Input.tsx
  src/constants/color.ts
  src/constants/messages.ts
  src/layout/Root.tsx
  src/pages/EditPwPage.tsx
  src/pages/LoginPage.tsx
Labels: ✨ Feature, 🔨 Refactor

#53 #34 프로필 페이지 구현
  src/App.tsx
  src/api/playlist/createPlayList.ts
  src/api/playlist/getPlayList.ts
  src/api/profile/profileInfo.ts
  src/assets/profile_logo.jpg
  src/constants/path.ts
  src/hooks/usePlaylistData.ts
  src/hooks/useUserData.ts
  src/pages/CreatePlaylistPage.tsx
  src/pages/ProfilePage.tsx
  src/types/playlistType.d.ts
  src/types/userType.d.ts
Labels: ✨ Feature

#51 ✨ #14 좋아요 기능 구현
  src/api/playlist/likePlaylist.ts
  src/components/LikeButton.tsx
  src/main.tsx
  src/pages/ChatPage.tsx
Labels: ✨ Feature

#50 ✨ #36 코멘트 탄스택 인피니티쿼리 적용
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/comment/getComment.ts
  src/components/Comments.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
Labels: ✨ Feature, 🔨 Refactor
