Repository Dev-FE-1/Toy_Project_3_Team1, pull requests merged in 2024-09, with the labels that each got.

#63 Fix/profile
  src/api/playlist/getPlayList.ts
  src/api/profile/profileInfo.ts
  src/hooks/usePlaylistData.ts
  src/hooks/usePlaylistDetail.ts
  src/hooks/useUserData.ts
  src/pages/ProfilePage.tsx
Labels: ☠️ Fix

#67 ☠️ #55 Link 컴포넌트 사용시 DOM요소로 불필요한 props 전달 문제 해결
  src/components/common/Button/Button.tsx
  src/components/common/Button/ButtonLink.tsx
  src/components/common/Input/Input.tsx
Labels: ☠️ Fix

#66 ☠️ #34 전체,공개,비공개 버튼 클릭 시 해당되는 컨텐츠 렌더링
  src/api/playlist/getPlayList.ts
  src/pages/ProfilePage.tsx
  src/types/playlistType.d.ts
Labels: ☠️ Fix

#58 #56 검색기능 구현완료 - css 적용 필요
  .github/PULL_REQUEST_TEMPLATE.md
  src/api/playlist/searchTag.ts
  src/components/LikeButton.tsx
  src/components/SearchPlaylist.tsx
  src/pages/SearchPage.tsx
Labels: ✨ Feature

#70 ☠️ #59 좋아요 프롭스, 타입에러 수정
  src/api/playlist/likePlaylist.ts
  src/components/LikeButton.tsx
Labels: 🔨 Refactor

#72 ☠️ #54 비공개로 플리를 추가할 수 있도록 체크박스 추가, 상태 추가
  src/api/playlist/createPlayList.ts
  src/pages/CreatePlaylistPage.tsx
Labels: ☠️ Fix

#84 🔨 #68 로그인 한 사용자 프로필, 타사용자 프로필 접속 시 다르게 보이도록 수정
  src/App.tsx
  src/api/playlist/getPlayList.ts
  src/api/profile/profileInfo.ts
  src/components/layout/Navbar.tsx
  src/constants/path.ts
  src/hooks/usePlaylistData.ts
  src/hooks/useUserData.ts
  src/hooks/useUserId.ts
  src/pages/ProfilePage.tsx
Labels: ☠️ Fix

#87 🔨 #85 로그인, 로그아웃, checkAuth, 구글로그인 auth 파일 추가
  src/components/layout/header/BackHeader.tsx
  src/components/layout/header/Header.tsx
  src/constants/path.ts
  src/hooks/useAuth.ts
  src/hooks/useLogout.ts
  src/layout/Root.tsx
  src/pages/EditProfilePage.tsx
  src/pages/LoginPage.tsx
  src/service/auth/checkAuth.ts
  src/service/auth/googleLogin.ts
  src/service/auth/login.ts
  src/service/auth/logout.ts
Labels: 🔨 Refactor

#89 ☠️ #85 인증된 사용자만 접근 가능한 라우팅설정 및 유저 프로필 페이지에서 로고가 표시되도록 Header 로직 수정
  src/App.tsx
  src/components/layout/header/Header.tsx
Labels: ☠️ Fix

#92 🔨 #85 팔로우한 사용자 및 로그인된 사용자의 플레이리스트 관련 기능 추가
  src/service/playlist/getFollowingUsersPlaylists.ts
  src/service/playlist/getUserPlaylistDetails.ts
  src/service/playlist/getUserPlaylists.ts
  src/utils/userDataUtils.ts
Labels: 🔨 Refactor

#98 🔨 #94 플리 목록, 플리 상세 목록 api 적용
  src/api/playlist/getPlayList.ts
  src/api/profile/profileInfo.ts
  src/components/layout/Navbar.tsx
  src/components/search/PlaylistThumbnails.tsx
  src/hooks/usePlaylistData.ts
  src/hooks/usePlaylistDetail.ts
  src/hooks/useUserData.ts
  src/hooks/useUserId.ts
  src/pages/ProfilePage.tsx
Labels: 🔨 Refactor

#102 📝 #101 로그인 한 사용자 프로필, 타사용자 프로필 헤더 다르게 적용
  src/App.tsx
  src/components/comments/CommentForm.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/LogoutHeader.tsx
  src/hooks/useIsMyProfile.ts
  src/hooks/useUserData.ts
  src/pages/EditProfilePage.tsx
  src/pages/PlaylistPage.tsx
  src/pages/ProfilePage.tsx
Labels: 📝 Design

#105 🔨 #85 #104 댓글 조회 API 수정 및 적용, 댓글 무한스크롤링 추가
  src/api/comment/addComment.ts
  src/api/comment/deleteComment.ts
  src/api/comment/getComment.ts
  src/components/comments/CommentCard.tsx
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentList.tsx
  src/components/comments/Comments.tsx
  src/service/comment/getAllCommentsByPlaylistId.ts
  src/service/comment/getPaginatedCommentsByPlaylistId.ts
  src/types/commentType.d.ts
Labels: 🔨 Refactor

#106 🔨☠️ #85 플레이리스트 추가 기능 API 완성 및 적용, 태그 공백시 에러처리
  src/api/playlist/createPlayList.ts
  src/api/profile/followService.ts
  src/api/profile/profileInfo.ts
  src/components/layout/Navbar.tsx
  src/constants/messages.ts
  src/hooks/useIsMyProfile.ts
  src/hooks/usePlaylistData.ts
  src/hooks/useTags.ts
  src/pages/CreatePlaylistPage.tsx
  src/service/playlist/createNewPlaylist.ts
  src/utils/userDataUtils.ts
Labels: 🔨 Refactor, ☠️ Fix

#110 ☠️ #109 댓글 작성 시 렌더링 제대로 안되는 이슈 수정
  src/components/comments/Comments.tsx
  src/constants/messages.ts
  src/hooks/usePLItem.ts
  src/pages/CreatePlaylistPage.tsx
Labels: ☠️ Fix

#114 ☠️ #113 댓글 삭제 버튼 안보이는 이슈 해결, 기능 작동 확인
  src/components/comments/CommentCard.tsx
Labels: ☠️ Fix

#116 ☠️ #115 추천 검색어 데이터 변경, api 생성, 서비스 폴더로 api 이동
  src/components/search/PlaylistItem.tsx
  src/components/search/RecommendKeyword.tsx
  src/components/search/RecommendSearch.tsx
  src/components/search/SearchSuccess.tsx
  src/hooks/useFollowStatus.ts
  src/hooks/useUserData.ts
  src/pages/SearchPage.tsx
  src/service/profile/followService.ts
  src/service/profile/profileInfo.ts
  src/service/search/getRecommendTags.ts
  src/service/search/searchTag.ts
Labels: ☠️ Fix

#118 ☠️ #115 비공개 플리로 업로드 된 태그는 검색 안되도록 수정
  src/components/search/SearchSuccess.tsx
  src/pages/SearchPage.tsx
  src/service/search/getRecommendTags.ts
  src/service/search/searchTag.ts
Labels: ☠️ Fix

#119 ✨🔨 #85 #117 사용자의 플레이리스트를 가져오는 함수 수정및 적용/타입변경, 아바타 컴포넌트 구현 및 적용
  src/assets/default-thumbnail.png
  src/components/comments/CommentCard.tsx
  src/components/common/Avatar.tsx
  src/components/playlist/MusicItem.tsx
  src/hooks/usePlaylistData.ts
  src/pages/PlaylistPage.tsx
  src/pages/ProfilePage.tsx
  src/service/playlist/getUserPlaylists.ts
  src/types/playlistType.d.ts
Labels: ✨ Feature, ☠️ Fix

#121 ☠️ #115 플리 최신순으로 나열되도록 정렬 추가
  src/components/playlist/MusicItem.tsx
  src/components/search/PlaylistThumbnails.tsx
  src/hooks/usePLItem.ts
  src/hooks/usePlaylistDetail.ts
  src/pages/ProfilePage.tsx
  src/service/playlist/createNewPlaylist.ts
  src/types/playlistType.d.ts
Labels: ☠️ Fix

#122 ✨ #85 홈피드 구현 및 플레이리스트 타입 정리
  src/components/MusicItem.tsx
  src/components/common/Button/LikeButton.tsx
  src/components/common/ImageGrid.tsx
  src/components/layout/Navbar.tsx
  src/components/playlist/MusicItem.tsx
  src/components/playlist/PlaylistThumbnailFeed.tsx
  src/components/playlist/TagList.tsx
  src/components/playlist/UserInfo.tsx
  src/components/search/PlaylistItem.tsx
  src/components/search/PlaylistThumbnails.tsx
  src/hooks/usePlaylistData.ts
  src/pages/CreatePlaylistPage.tsx
  src/pages/HomePage.tsx
  src/pages/PlaylistPage.tsx
  src/pages/ProfilePage.tsx
  src/service/playlist/getFollowingUsersPlaylists.ts
  src/service/playlist/getPaginatedFollowingUsersPlaylists.ts
  src/service/playlist/getUserPlaylists.ts
  src/service/playlist/likePlaylist.ts
  src/types/playlistType.d.ts
Labels: ✨ Feature

#126 Refactor/playlist
  src/App.tsx
  src/components/playlist/MusicItem.tsx
  src/constants/messages.ts
  src/hooks/usePlaylistDetail.ts
  src/pages/CreatePlaylistPage.tsx
  src/pages/PlaylistPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ResetPwPage.tsx
Labels: 🔨 Refactor

#127 🔨 라우터과 layout 등 프로젝트 공통부분 코드리뷰수정
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/np_logo.svg
  src/components/comments/CommentCard.tsx
  src/components/comments/CommentForm.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/ButtonLink.tsx
  src/components/common/Button/LikeButton.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/LineInput.tsx
  src/components/common/Loading.tsx
  src/components/layout/Navbar.tsx
  src/components/layout/header/BackHeader.tsx
  src/components/layout/header/Header.tsx
  src/components/layout/header/LogoutHeader.tsx
  src/components/playlist/MusicItem.tsx
  src/components/playlist/TagList.tsx
  src/components/playlist/UserInfo.tsx
  src/components/search/PlaylistItem.tsx
  src/components/search/RecommendKeyword.tsx
  src/components/search/SearchFail.tsx
  src/components/search/SearchSuccess.tsx
  src/constants/firebaseKeys.ts
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthQuery.ts
  src/layout/Root.tsx
  src/main.tsx
  src/pages/CreatePlaylistPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/NotFoundPage.tsx
  src/pages/Page404.tsx
  src/pages/PlaylistPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ResetPwPage.tsx
  src/pages/SearchPage.tsx
  src/routes/PrivateRoute.tsx
  src/routes/index.tsx
  src/service/auth/checkAuth.ts
  src/service/auth/googleLogin.ts
  src/service/auth/logout.ts
  src/stores/useAuthStore.tsx
  src/styles/GlobalStyles.tsx
  src/styles/colors.ts
  src/styles/font.ts
Labels: 🔨 Refactor
